services:
  - type: web
    name: fenomenalfunds-frontend-qa
    env: static
    plan: starter
    repo: https://github.com/fenomenalfunds/fenomenal-funds-frontend.git
    branch: staging
    buildCommand: yarn; yarn build; yarn next export #npm install && npm run build
    staticPublishPath: out
    healthCheckPath: /_health