services:
  - type: web
    name: fenomenalfunds-frontend-qa
    env: node
    plan: standard
    repo: https://github.com/fenomenalfunds/fenomenal-funds-frontend.git
    branch: staging
    buildCommand: yarn; yarn build #npm install && npm run build
    startCommand: yarn start #npm start
    healthCheckPath: /_health
    envVars:
    - key: STRAPI_API_URL
      value: 'https://cms-staging.fenomenalfunds.org'