services:
  - type: web
    name: fenomenalfunds-frontend-qa
    env: node
    plan: standard
    repo: https://github.com/fenomenalfunds/fenomenal-funds-frontend.git
    branch: staging
    buildCommand: npm install && npm run build
    startCommand: npx next start -p 10000
    healthCheckPath: /_health
    envVars:
    - key: STRAPI_API_URL
      value: 'https://cms-staging.fenomenalfunds.org'
    - key: NODE_ENV
      value: production